import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/features/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "../../packages/ui/src/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-sans)"],
        anton: ["var(--font-anton)"],
        bebas: ["var(--font-bebas)"],
        oswald: ["var(--font-oswald)"],
        pathway: ["var(--font-pathway)"],
        fjalla: ["var(--font-fjalla)"],
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: "var(--primary)",
        secondary: "var(--secondary)",
        warning: "var(--warning)",
        danger: "var(--danger)",
      },
      keyframes: {
        float: { "0%, 100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-8px)" } },
        floatReverse: { "0%, 100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(8px)" } },
        floatRandom1: { "0%, 100%": { transform: "translate(0, 0)" }, "33%": { transform: "translate(4px, -6px)" }, "66%": { transform: "translate(-3px, 5px)" } },
        floatRandom2: { "0%, 100%": { transform: "translate(0, 0)" }, "33%": { transform: "translate(-5px, 4px)" }, "66%": { transform: "translate(6px, -3px)" } },
        floatRandom3: { "0%, 100%": { transform: "translate(0, 0)" }, "33%": { transform: "translate(3px, 5px)" }, "66%": { transform: "translate(-4px, -6px)" } },
        floatRandom4: { "0%, 100%": { transform: "translate(0, 0)" }, "33%": { transform: "translate(-6px, -4px)" }, "66%": { transform: "translate(5px, 3px)" } },
        pulseRing: { "0%": { transform: "scale(0.8)", opacity: "1" }, "100%": { transform: "scale(1.4)", opacity: "0" } },
        fadeInUp: { "0%": { opacity: "0", transform: "translateY(10px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        smoke: { "0%": { transform: "translateY(0) scale(1)", opacity: "0.6" }, "100%": { transform: "translateY(-60px) scale(1.3)", opacity: "0" } },
        reveal: { from: { clipPath: "inset(0 100% 0 0)" }, to: { clipPath: "inset(0 0 0 0)" } },
        shimmer: { "0%": { backgroundPosition: "-1000px 0" }, "100%": { backgroundPosition: "1000px 0" } },
        pulseBorder: { "0%, 100%": { borderColor: "rgba(120, 200, 65, 0.3)" }, "50%": { borderColor: "rgba(120, 200, 65, 0.8)" } },
      },
      animation: {
        "float-slow": "float 6s ease-in-out infinite",
        "float-medium": "float 4s ease-in-out infinite",
        "float-reverse": "floatReverse 5s ease-in-out infinite",
        "float-random-1": "floatRandom1 7s ease-in-out infinite",
        "float-random-2": "floatRandom2 8s ease-in-out infinite",
        "float-random-3": "floatRandom3 6.5s ease-in-out infinite",
        "float-random-4": "floatRandom4 7.5s ease-in-out infinite",
        "pulse-ring": "pulseRing 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "fade-in-up": "fadeInUp 0.6s ease-out",
        "smoke-1": "smoke 3s ease-out infinite",
        "smoke-2": "smoke 3.5s ease-out infinite 0.5s",
        "smoke-3": "smoke 4s ease-out infinite 1s",
        "smoke-orange-1": "smoke 2.8s ease-out infinite",
        "smoke-orange-2": "smoke 3.2s ease-out infinite 0.6s",
        "smoke-orange-3": "smoke 3.6s ease-out infinite 1.2s",
        "smoke-green-1": "smoke 3.1s ease-out infinite",
        "smoke-green-2": "smoke 3.4s ease-out infinite 0.7s",
        "smoke-green-3": "smoke 3.8s ease-out infinite 1.4s",
        "smoke-green-4": "smoke 4.2s ease-out infinite 2.1s",
        reveal: "reveal 0.8s ease-out forwards",
        shimmer: "shimmer 2s linear infinite",
        "pulse-border": "pulseBorder 2s ease-in-out infinite",
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
    },
  },
  plugins: [],
};
export default config;
