// Countries list for nationality select
export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Argentina",
  "Australia",
  "Austria",
  "Bangladesh",
  "Belgium",
  "Brazil",
  "Cambodia",
  "Canada",
  "Chile",
  "China",
  "Colombia",
  "Czech Republic",
  "Denmark",
  "Egypt",
  "Finland",
  "France",
  "Germany",
  "Greece",
  "Hong Kong",
  "Hungary",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Korea (North)",
  "Korea (South)",
  "Kuwait",
  "Laos",
  "Lebanon",
  "Malaysia",
  "Mexico",
  "Morocco",
  "Myanmar",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "Norway",
  "Pakistan",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Saudi Arabia",
  "Singapore",
  "South Africa",
  "Spain",
  "Sri Lanka",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Thailand",
  "Turkey",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Vietnam",
  "Other"
];

// Vietnamese names for countries (for display in Vietnamese UI)
export const countriesVi: Record<string, string> = {
  "Afghanistan": "Afghanistan",
  "Albania": "Albania",
  "Algeria": "Algérie",
  "Argentina": "Argentina",
  "Australia": "Úc",
  "Austria": "Áo",
  "Bangladesh": "Bangladesh",
  "Belgium": "Bỉ",
  "Brazil": "Brazil",
  "Cambodia": "Campuchia",
  "Canada": "Canada",
  "Chile": "Chile",
  "China": "Trung Quốc",
  "Colombia": "Colombia",
  "Czech Republic": "Cộng hòa Séc",
  "Denmark": "Đan Mạch",
  "Egypt": "Ai Cập",
  "Finland": "Phần Lan",
  "France": "Pháp",
  "Germany": "Đức",
  "Greece": "Hy Lạp",
  "Hong Kong": "Hồng Kông",
  "Hungary": "Hungary",
  "India": "Ấn Độ",
  "Indonesia": "Indonesia",
  "Iran": "Iran",
  "Iraq": "Iraq",
  "Ireland": "Ireland",
  "Israel": "Israel",
  "Italy": "Ý",
  "Japan": "Nhật Bản",
  "Jordan": "Jordan",
  "Kazakhstan": "Kazakhstan",
  "Kenya": "Kenya",
  "Korea (North)": "Triều Tiên",
  "Korea (South)": "Hàn Quốc",
  "Kuwait": "Kuwait",
  "Laos": "Lào",
  "Lebanon": "Lebanon",
  "Malaysia": "Malaysia",
  "Mexico": "Mexico",
  "Morocco": "Ma-rốc",
  "Myanmar": "Myanmar",
  "Nepal": "Nepal",
  "Netherlands": "Hà Lan",
  "New Zealand": "New Zealand",
  "Nigeria": "Nigeria",
  "Norway": "Na Uy",
  "Pakistan": "Pakistan",
  "Peru": "Peru",
  "Philippines": "Philippines",
  "Poland": "Ba Lan",
  "Portugal": "Bồ Đào Nha",
  "Qatar": "Qatar",
  "Romania": "Romania",
  "Russia": "Nga",
  "Saudi Arabia": "Ả Rập Xê Út",
  "Singapore": "Singapore",
  "South Africa": "Nam Phi",
  "Spain": "Tây Ban Nha",
  "Sri Lanka": "Sri Lanka",
  "Sweden": "Thụy Điển",
  "Switzerland": "Thụy Sĩ",
  "Taiwan": "Đài Loan",
  "Thailand": "Thái Lan",
  "Turkey": "Thổ Nhĩ Kỳ",
  "Ukraine": "Ukraine",
  "United Arab Emirates": "UAE",
  "United Kingdom": "Anh",
  "United States": "Hoa Kỳ",
  "Vietnam": "Việt Nam",
  "Other": "Khác"
};

// Get country name in Vietnamese
export function getCountryNameVi(country: string): string {
  return countriesVi[country] || country;
}

// Get all countries
export function getAllCountries(): string[] {
  return countries;
}
